language: ruby
dist: trusty
rvm:
  - 2.4
before_script:
  - cd ./test
  - bundle exec rackup -r grr -s grr config.ru -o 0.0.0.0 -p 6575 &
  - ruby ./app.rb &
  - sleep 5
notifications:
  slack:
    rooms:
      - hpi:ndJzCSHEaofBnyHTHURo0DFO
    on_success: change
    on_pull_requests: false
    template:
          - "Build <%{build_url}|#%{build_number}> of <%{compare_url}|%{branch}> by %{author} %{result}."
          - "> %{commit_message}"
  email: false